# -*- coding: utf-8 -*-
"""Copy of Midterm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XalcWDbvcuDhMuH7oZcbP2CtbT-qpBwb
"""

!pip install ortools
!pip install fitter

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('done')

df = pd.read_csv('date_cleaned_1.csv')

df.info()

df['Acquisition_Cost'] = df['Acquisition_Cost'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)
campaign_type_metrics = df.groupby('Campaign_Type')[['Conversion_Rate', 'Acquisition_Cost', 'ROI']].mean().reset_index()
print(campaign_type_metrics)

"""## Plot Conversion Rate Histograms by Campaign Type"""

# @title
unique_campaign_types = df['Campaign_Type'].unique()

for campaign_type in unique_campaign_types:
    # Filter the DataFrame for the current campaign type
    filtered_df = df[df['Campaign_Type'] == campaign_type]

    # Create a histogram for 'Conversion_Rate'
    plt.figure(figsize=(8, 5))
    sns.histplot(filtered_df['Conversion_Rate'], bins=20, kde=True)
    plt.title(f'Conversion Rate Distribution for {campaign_type}')
    plt.xlabel('Conversion Rate')
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()

"""## Plot Acquisition Cost Histograms by Campaign Type

"""

# @title
unique_campaign_types = df['Campaign_Type'].unique()

for campaign_type in unique_campaign_types:
    # Filter the DataFrame for the current campaign type
    filtered_df = df[df['Campaign_Type'] == campaign_type]

    # Create a histogram for 'Acquisition_Cost'
    plt.figure(figsize=(8, 5))
    sns.histplot(filtered_df['Acquisition_Cost'], bins=20, kde=True)
    plt.title(f'Acquisition Cost Distribution for {campaign_type}')
    plt.xlabel('Acquisition Cost')
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()

"""## Plot ROI Histograms by Campaign Type

"""

# @title
for campaign_type in unique_campaign_types:
    # Filter the DataFrame for the current campaign type
    filtered_df = df[df['Campaign_Type'] == campaign_type]

    # Create a histogram for 'ROI'
    plt.figure(figsize=(8, 5))
    sns.histplot(filtered_df['ROI'], bins=20, kde=True)
    plt.title(f'ROI Distribution for {campaign_type}')
    plt.xlabel('ROI')
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()

"""# Task
Install the `fitter` library, then for each unique `Campaign_Type` and for each of the 'Conversion_Rate', 'Acquisition_Cost', and 'ROI' metrics, find the best-fit probability distribution and its parameters using the `Fitter` library.
"""

from fitter import Fitter

metrics_to_fit = ['Conversion_Rate', 'Acquisition_Cost', 'ROI']
results = {}

for campaign_type in df['Campaign_Type'].unique():
    results[campaign_type] = {}
    for metric in metrics_to_fit:
        print(f"Fitting distributions for {campaign_type} - {metric}...")
        data = df[df['Campaign_Type'] == campaign_type][metric].dropna()

        # Some distributions in fitter might fail if data contains zeros or negative values,
        # especially for metrics like Conversion_Rate or ROI which should be non-negative.
        # Acquisition_Cost should also be non-negative. We'll filter out zeros if any
        # distribution type is sensitive to it and it makes sense in context.
        if metric == 'Conversion_Rate':
            data = data[data > 0] # Conversion Rate can be 0, but some distributions might not handle it well.
        elif metric == 'ROI':
            data = data[data > 0] # ROI can be negative, but fitter's default distributions might not handle it well

        if not data.empty:
            f = Fitter(data, distributions=['norm', 'expon', 'gamma', 'lognorm', 'beta'])
            f.fit()
            results[campaign_type][metric] = f.get_best(method='sumsquare_error')
            print(f"Best fit for {campaign_type} - {metric}: {results[campaign_type][metric]}")
        else:
            results[campaign_type][metric] = "No data to fit"
            print(f"No data to fit for {campaign_type} - {metric}")

print("\nFitting process complete. Results stored in 'results' dictionary.")

print("\n--- Best-Fit Distribution Summary ---")
for campaign_type, metrics_data in results.items():
    print(f"\nCampaign Type: {campaign_type}")
    for metric, best_fit_info in metrics_data.items():
        if best_fit_info != "No data to fit":
            dist_name = list(best_fit_info.keys())[0]
            params = best_fit_info[dist_name]
            print(f"  Metric: {metric}")
            print(f"    Best-fit distribution: {dist_name}")
            print(f"    Parameters: {params}")
        else:
            print(f"  Metric: {metric}")
            print(f"    {best_fit_info}")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ortools.linear_solver import pywraplp

# 1. Setup Parameters
campaigns = ['Display', 'Email', 'Influencer', 'Search', 'Social Media']
total_budget = 75000
n_simulations = 200000  # Updated to 200,000 runs

# Best-fit Parameters from Notebook
cr_dist_info = {
    'Email': {'dist': 'norm', 'params': (0.02500, 0.00799)},
    'Influencer': {'dist': 'gamma', 'params': (116989.65, -6.739, 5.837e-05)},
    'Display': {'dist': 'norm', 'params': (0.01200, 0.00397)},
    'Search': {'dist': 'beta', 'params': (55.307, 52.688, -0.093, 0.416)},
    'Social Media': {'dist': 'beta', 'params': (10807084, 422714, -253.9, 263.9)}
}

ac_dist_info = {
    'Email': {'dist': 'norm', 'params': (2500.20, 795.47)},
    'Influencer': {'dist': 'beta', 'params': (74539.3, 1654219.9, -819793.9, 19430028.4)},
    'Display': {'dist': 'beta', 'params': (139.86, 110.94, -13266.1, 31859.7)},
    'Search': {'dist': 'beta', 'params': (46272.8, 2351047.2, -426249.8, 22652561.6)},
    'Social Media': {'dist': 'beta', 'params': (2018971, 341536, -5613084, 6571963)}
}

def sample_dist(dist_type, params, size):
    if dist_type == 'norm':
        return np.random.normal(params[0], params[1], size)
    elif dist_type == 'gamma':
        return np.random.gamma(params[0], params[2], size) + params[1]
    elif dist_type == 'beta':
        return np.random.beta(params[0], params[1], size) * params[3] + params[2]
    return np.zeros(size)

# Sample all values at once
sampled_cr = {c: sample_dist(cr_dist_info[c]['dist'], cr_dist_info[c]['params'], n_simulations) for c in campaigns}
sampled_ac = {c: sample_dist(ac_dist_info[c]['dist'], ac_dist_info[c]['params'], n_simulations) for c in campaigns}

# 2. Run Simulation using OR-Tools
allocations = {c: [] for c in campaigns}

for i in range(n_simulations):
    conv_per_dollar = {c: float(max(0, sampled_cr[c][i]) / max(1e-6, sampled_ac[c][i])) for c in campaigns}

    solver = pywraplp.Solver.CreateSolver('GLOP')
    # Constraints: 5% Min floor, No Max ceiling
    x = {c: solver.NumVar(0.05 * total_budget, total_budget, c) for c in campaigns}
    solver.Add(solver.Sum(x.values()) == total_budget)

    objective = solver.Objective()
    for c in campaigns:
        objective.SetCoefficient(x[c], conv_per_dollar[c])
    objective.SetMaximization()

    if solver.Solve() == pywraplp.Solver.OPTIMAL:
        for c in campaigns:
            allocations[c].append((x[c].solution_value() / total_budget) * 100)

# 3. Visualization
fig, axes = plt.subplots(1, 5, figsize=(22, 5), sharey=True)
colors = sns.color_palette("husl", 5)

for i, campaign in enumerate(campaigns):
    sns.histplot(allocations[campaign], bins=20, ax=axes[i], color=colors[i], stat='count')
    axes[i].set_title(f'{campaign} Allocation')
    axes[i].set_xlabel('Budget %')
    axes[i].set_xlim(0, 100)
    # Zoom in: set max y-limit to 200,000
    axes[i].set_ylim(0, 200000)
    axes[i].axvline(5, color='black', linestyle='--', alpha=0.3)

plt.suptitle(f'Budget Allocation (200,000 runs)', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""# Run Optimization Maximizing for ROI"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fitter import Fitter
from ortools.linear_solver import pywraplp
import scipy.stats as stats
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 1. SETUP & FIT DISTRIBUTIONS
# ==========================================
# (Assuming df is already loaded and cleaned from the top of your notebook)
campaigns = df['Campaign_Type'].unique().tolist()
metrics_to_fit = ['ROI']
results = {}

print("Fitting distributions for ROI by Campaign Type...")
for campaign in campaigns:
    results[campaign] = {}

    # Filter for specific campaign and ROI metric
    data = df[df['Campaign_Type'] == campaign]['ROI'].dropna()
    data = data[data > 0] # Filter out zeros/negatives

    if not data.empty:
        f = Fitter(data, distributions=['norm', 'expon', 'gamma', 'lognorm', 'beta'])
        f.fit(progress=False)
        results[campaign]['ROI'] = f.get_best(method='sumsquare_error')
    else:
        results[campaign]['ROI'] = "No data to fit"

print("\n--- Best-Fit Distribution Summary ---")
for campaign, metrics_data in results.items():
    print(f"\nCampaign Type: {campaign}")
    best_fit_info = metrics_data['ROI']
    if best_fit_info != "No data to fit":
        dist_name = list(best_fit_info.keys())[0]
        params = best_fit_info[dist_name]
        print(f"  Metric: ROI -> Best-fit: {dist_name} | Params: {params}")

# ==========================================
# 2. RUN MONTE CARLO SIMULATION
# ==========================================
total_budget = 75000
n_simulations = 200000

# UPDATED: Use scipy.stats to handle the fitter dictionary directly!
def sample_dist(dist_type, params, size):
    dist = getattr(stats, dist_type)
    return dist.rvs(**params, size=size)

# Sample the simulated ROI futures 200,000 times
sampled_roi = {}
for campaign in campaigns:
    dist_info = results[campaign]['ROI']
    dist_name = list(dist_info.keys())[0]
    params = dist_info[dist_name]
    sampled_roi[campaign] = sample_dist(dist_name, params, n_simulations)

allocations = {c: [] for c in campaigns}

print("\nRunning OR-Tools Optimization...")
for i in range(n_simulations):
    # Get the simulated ROI for this specific run
    roi_values = {c: float(max(0, sampled_roi[c][i])) for c in campaigns}

    solver = pywraplp.Solver.CreateSolver('GLOP')

    # Constraints: 5% Min floor, No Max ceiling
    x = {c: solver.NumVar(0.05 * total_budget, total_budget, c) for c in campaigns}
    solver.Add(solver.Sum(x.values()) == total_budget)

    # Objective: Maximize total generated ROI Return
    objective = solver.Objective()
    for c in campaigns:
        objective.SetCoefficient(x[c], roi_values[c])
    objective.SetMaximization()

    if solver.Solve() == pywraplp.Solver.OPTIMAL:
        for c in campaigns:
            allocations[c].append((x[c].solution_value() / total_budget) * 100)

# ==========================================
# 3. VISUALIZATION
# ==========================================
fig, axes = plt.subplots(1, len(campaigns), figsize=(22, 5), sharey=True)
colors = sns.color_palette("husl", len(campaigns))

for i, campaign in enumerate(campaigns):
    sns.histplot(allocations[campaign], bins=20, ax=axes[i], color=colors[i], stat='count')
    axes[i].set_title(f'{campaign} Allocation', fontsize=14, fontweight='bold')
    axes[i].set_xlabel('Budget %')
    axes[i].set_xlim(0, 100)

    # Scale Y-axis to account for the 200,000 runs
    axes[i].set_ylim(0, 200000)
    axes[i].axvline(5, color='black', linestyle='--', alpha=0.3)

plt.suptitle(f'Overall Budget Allocation Maximizing ROI ({n_simulations} runs)', fontsize=18)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""# Rerun Based on Our Own Engagement Metric

To create a true representation of engagement, we can combine three specific columns: Clicks, Impressions, and Engagement_Score.

Click-Through Rate (CTR): We calculate Clicks / Impressions to see what percentage of people actually stopped scrolling and clicked.

Quality: We multiply that percentage by the 1-10 Engagement_Score. A high CTR with a low Engagement Score (e.g., clickbait) will be penalized, while a decent CTR with a perfect 10 Engagement Score will be heavily rewarded.

We divide the whole thing by Acquisition_Cost to see how many "Engagement Points" the company gets for every $1 spent.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fitter import Fitter
from ortools.linear_solver import pywraplp
import scipy.stats as stats
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 1. LOAD DATA & CREATE CUSTOM METRIC
# ==========================================
df = pd.read_csv('date_cleaned_1.csv')
df['Acquisition_Cost'] = df['Acquisition_Cost'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

# Math: (CTR * Engagement Score * 1000) / Acquisition_Cost
df['True_Engagement_Points'] = (df['Clicks'] / df['Impressions']) * df['Engagement_Score'] * 1000
df['Engagement_Per_Dollar'] = df['True_Engagement_Points'] / df['Acquisition_Cost']

campaigns = df['Campaign_Type'].unique().tolist()
results = {}

print("Fitting distributions for Custom Engagement Metric by Campaign Type...")
for campaign in campaigns:
    results[campaign] = {}

    data = df[df['Campaign_Type'] == campaign]['Engagement_Per_Dollar'].dropna()
    data = data[data > 0]

    if not data.empty:
        f = Fitter(data, distributions=['norm', 'expon', 'gamma', 'lognorm', 'beta'])
        f.fit(progress=False)
        results[campaign]['Engagement'] = f.get_best(method='sumsquare_error')
    else:
        results[campaign]['Engagement'] = "No data to fit"

# --> ADDED: PRINTING THE PARAMETERS HERE <--
print("\n--- Best-Fit Distribution Summary ---")
for campaign, metrics_data in results.items():
    print(f"\nCampaign Type: {campaign}")
    best_fit_info = metrics_data['Engagement']

    if best_fit_info != "No data to fit":
        # Extract the dictionary name (e.g., 'norm', 'beta')
        dist_name = list(best_fit_info.keys())[0]
        # Extract the dictionary containing the actual parameters
        params = best_fit_info[dist_name]

        print(f"  Metric: Engagement_Per_Dollar")
        print(f"    Best-fit distribution: {dist_name}")
        print(f"    Parameters: {params}")

# ==========================================
# 2. RUN MONTE CARLO SIMULATION
# ==========================================
total_budget = 75000
n_simulations = 100000

def sample_dist(dist_type, params, size):
    dist = getattr(stats, dist_type)
    return dist.rvs(**params, size=size)

sampled_eng = {}
for campaign in campaigns:
    dist_info = results[campaign]['Engagement']
    dist_name = list(dist_info.keys())[0]
    params = dist_info[dist_name]
    sampled_eng[campaign] = sample_dist(dist_name, params, n_simulations)

allocations = {c: [] for c in campaigns}

print("\nRunning OR-Tools Optimization...")
for i in range(n_simulations):
    eng_values = {c: float(max(0, sampled_eng[c][i])) for c in campaigns}

    solver = pywraplp.Solver.CreateSolver('GLOP')

    x = {c: solver.NumVar(0.05 * total_budget, total_budget, c) for c in campaigns}
    solver.Add(solver.Sum(x.values()) == total_budget)

    objective = solver.Objective()
    for c in campaigns:
        objective.SetCoefficient(x[c], eng_values[c])
    objective.SetMaximization()

    if solver.Solve() == pywraplp.Solver.OPTIMAL:
        for c in campaigns:
            allocations[c].append((x[c].solution_value() / total_budget) * 100)

# ==========================================
# 3. VISUALIZATION
# ==========================================
fig, axes = plt.subplots(1, len(campaigns), figsize=(22, 5), sharey=True)
colors = sns.color_palette("muted", len(campaigns))

for i, campaign in enumerate(campaigns):
    sns.histplot(allocations[campaign], bins=20, ax=axes[i], color=colors[i], stat='count', element='step', alpha=0.6)
    axes[i].set_title(f'{campaign} Allocation', fontsize=14, fontweight='bold')
    axes[i].set_xlabel('Budget %')
    axes[i].set_xlim(0, 100)
    axes[i].set_ylim(0, 100000)
    axes[i].axvline(5, color='black', linestyle='--', alpha=0.3)

plt.suptitle(f'Overall Budget Allocation Maximizing Custom Engagement Score ({n_simulations} runs)', fontsize=18)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()